# Generated by Django 5.2.10 on 2026-01-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_late_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
