# Generated by Django 5.2.10 on 2026-01-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member_is_late_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='community',
            new_name='com_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='user_id',
        ),
    ]
