# Generated by Django 6.0.1 on 2026-01-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
