# Generated by Django 5.2.10 on 2026-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chat_options_alter_chat_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
