# Generated by Django 5.2.10 on 2026-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='shame_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='shame/'),
        ),
    ]
