"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    DEBUG=(bool, False) # 기본값은 False
)
# .env 파일이 있으면 읽어옴 (로컬 개발용)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6k2pc5(ay%8*0f9t!h7y@5+@uc1x!(yg8if_!6y_z$!6i5hv(d"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = ['*']

# 1. CSRF 신뢰할 수 있는 오리진 추가 (정우님의 배포 주소)
CSRF_TRUSTED_ORIGINS = [
    'https://ddyeo-backend-1003047877852.asia-northeast3.run.app',
]

# 2. 프록시 헤더 설정 (Cloud Run과 같은 환경에서 HTTPS 인식을 위해 필수)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'daphne',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'django_apscheduler',
    'channels',
    'api'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'api.authentication.UserIdAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

IS_GCP = os.getenv('K_SERVICE') or os.getenv('CLOUD_RUN_JOB')


if IS_GCP:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'madcamp_db',         # 2단계에서 만든 DB 이름
            'USER': 'admin',         # 2단계에서 만든 사용자
            'PASSWORD': env('DB_PASS'),   # 설정하신 비밀번호
            'HOST': f'/cloudsql/madcamp-w2-backend:asia-northeast3:madcamp-w2-db',
        }
    }
else:
    # 기존 로컬 Docker 설정 유지
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'bereal_db',
            'USER': 'postgres',
            'PASSWORD': '1020',
            'HOST': 'db',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'api.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    # "https://your-frontend-vercel-url.com", 
]
CORS_ALLOW_ALL_ORIGINS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# GCS 이미지 저장소 연결
INSTALLED_APPS += ['storages']

# GCS 설정
# 1. GCS 버킷 이름 및 권한 설정
GS_BUCKET_NAME = 'madcamp-w2-storage'  # 정우님의 실제 버킷 이름으로 설정
GS_DEFAULT_ACL = 'publicRead'           # GCS 파일 업로드 시 공개 읽기 권한 부여

# 로컬 테스트 시에는 JSON 키 파일 경로를, 배포 시에는 IAM 사용
# GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
#     os.path.join(BASE_DIR, os.getenv('GS_CREDENTIALS', 'config/gcp-key.json'))
# )

GS_CREDENTIALS_PATH = os.path.join(BASE_DIR, os.getenv('GS_CREDENTIALS', 'config/gcp-key.json'))

if os.path.exists(GS_CREDENTIALS_PATH):
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(GS_CREDENTIALS_PATH)
else:
    # 파일이 없으면 None으로 둡니다. (GCP 환경은 기본 서비스 계정 권한을 자동으로 사용함)
    GS_CREDENTIALS = None

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    # 유저 모델에서 주 키(PK)로 사용하는 필드명을 지정합니다.
    'USER_ID_FIELD': 'user_id', 
    
    # 토큰 내부에 저장될 유저 식별자의 키 이름을 지정합니다.
    'USER_ID_CLAIM': 'user_id',
    
    # (선택 사항) 토큰 만료 시간 설정
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Redis 등록을 위한 채널 레이어 설정
if IS_GCP:
    # 배포 환경에서는 Redis 주소가 달라질 수 있습니다 (GCP MemoryStore 등 사용 시)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer', # 일단 인메모리로 설정하여 에러 방지
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [('redis', 6379)],
            },
        },
    }